# Generated by Django 5.0.4 on 2024-04-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patientappointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='admitted_or_not',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='no', max_length=5),
        ),
    ]
