# Generated by Django 5.0.4 on 2024-04-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='supports_covid19',
            field=models.BooleanField(default=True),
        ),
    ]
